apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: game-server-load-test
  namespace: production
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-load-test
      file: k6-load-test.js
  runner:
    image: grafana/k6:latest
    env:
      - name: K6_OUT
        value: json=test-results.json
  arguments: --address 0.0.0.0:6565
