apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-server-{{ .Values.env }}
  namespace: production
  labels:
    app: game-server
    env: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: game-server
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: game-server
        env: {{ .Values.env }}
    spec:
      containers:
      - name: game-server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          {{ toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5