apiVersion: v1
kind: Service
metadata:
  name: game-server-{{ .Values.env }}
  namespace: production
  labels:
    app: game-server
    env: {{ .Values.env }}
spec:
  selector:
    app: game-server
    env: {{ .Values.env }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
  type: {{ .Values.service.type }}